buildscript {
    repositories {
        mavenCentral()
        maven { url "https://files.minecraftforge.net/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = '1.0-Premium'
group = 'com.amongus'
archivesBaseName = 'among-us-client'

sourceCompatibility = targetCompatibility = 1.8

minecraft {
    version = '1.8.9-11.15.1.2318-1.8.9'
    runDir = 'run'
    mappings = 'stable_22'
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'net.java.dev.jna:jna:5.13.0'
    compile 'net.java.dev.jna:jna-platform:5.13.0'
    compile 'org.ow2.asm:asm:9.5'
    compile 'org.ow2.asm:asm-commons:9.5'
}

jar {
    manifest {
        attributes 'Premain-Class': 'com.amongus.client.injector.AgentMain',
                   'Agent-Class': 'com.amongus.client.injector.AgentMain',
                   'Can-Retransform-Classes': 'true',
                   'Can-Redefine-Classes': 'true',
                   'Implementation-Title': 'among us client Premium',
                   'Class-Path': configurations.compile.collect { it.getName() }.join(' ')
    }
}

// Copy dependencies to build/libs
task copyDeps(type: Copy) {
    from configurations.compile
    into 'build/libs'
}

// Create distribution zip (depends on jar and copyDeps, not on build)
task distZip(type: Zip) {
    baseName = 'among-us-client-bundle'
    destinationDir = file('build/libs')
    from('build/libs') {
        include '*.jar'
        exclude 'among-us-client-bundle.zip'
    }
    dependsOn jar, copyDeps   // no cycle
}

// Make the default build task produce the distribution zip
build.dependsOn distZip
